title: Your Health & Wealth Source
author: JoeKirby3
email: joekirby333@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Together, we can learn how to build our health & wealth!

# social links
twitter_username: gottalovekirby # DO NOT include the @ character, or else the build will fail!
github_username:  JoeKirby3 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
